global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules/monitoring_alerts.yml"

scrape_configs:
  - job_name: "monitoring"
    static_configs:
      - targets:
          - "monitoring:9400"
        labels:
          site: example-site